language: csharp
os: windows
solution: BasicVideoChat/BasicVideoChat.sln
mono: none
install:
    - choco install nuget.commandline
    - nuget restore BasicVideoChat.sln
before_script:
    - export PATH=$PATH:"/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
    - cd BasicVideoChat
script:
    - MSBuild.exe