language: csharp
solution: BasicVideoChat/BasicVideoChat.sln
dist: xenial
addons:
    snaps:
      - name: dotnet-sdk
        confinement: classic
        channel: 3.1/stable
install:
    - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/